query_image:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: extended_openai_conversation
    model:
      example: gpt-4-vision-preview
      selector:
        text:
    prompt:
      example: "What's in this image?"
      required: true
      selector:
        text:
          multiline: true
    images:
      example: '{"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg"}'
      required: true
      default: []
      selector:
        object:
    max_tokens:
      example: 300
      default: 300
      selector:
        number:
          min: 1
          mode: box

clear_conversations:
  description: "Clear conversation history from memory store"
  fields:
    conversation_id:
      description: "Optional conversation ID to clear. If not provided, all conversations will be cleared."
      example: "01H1TXKTWZYWNCP6ZDC9WKH4QP"
      required: false
      selector:
        text:
